Changed to test with wget

diff --git a/.github/workflows/test-docker-image.yml b/.github/workflows/test-docker-image.yml
--- a/.github/workflows/test-docker-image.yml
+++ b/.github/workflows/test-docker-image.yml
@@ -26,5 +26,10 @@ jobs:
 
     - name: Test Application
       run: |
-        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8001/predict
+        wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 -qO- --spider http://localhost:8001/predict
+        if [ $? -ne 0 ]; then
+          echo "Failed to connect with the Application" && exit 1
+        else 
+          echo "Application is up and running"
+        fi
 
